manifest:
  remotes:
    - name: JVViacrusis
      url-base: https://github.com/JVViacrusis
  projects:
    - name: zmk
      remote: JVViacrusis
      revision: main
      import: app/west.yml
  self:
    path: config
